version: '3.8'
services:
    db:
        container_name: db_php
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'db_php'
        ports:
            - '3307:3306'
        volumes:
            - ./data/:/var/lib/mysql